param(
  [string]$InstallRoot = (Join-Path $env:USERPROFILE "trueRiver"),
  [string[]]$SourcePath = @()
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\Common.ps1"

function ConvertTo-TriverSourceKey {
  param([string]$Value)
  $slug = ($Value.ToLowerInvariant() -replace "[^a-z0-9_-]+", "-").Trim("-")
  if (-not $slug) {
    return "source"
  }
  return $slug
}

function ConvertTo-YamlQuoted {
  param([string]$Value)
  return '"' + ($Value.Replace('\', '\\').Replace('"', '\"')) + '"'
}

$repoRoot = Get-TriverRepoRoot
$paths = Get-TriverInstallPaths $InstallRoot
$envFile = Join-Path $paths.Local ".env"
$extraCompose = Join-Path $paths.Local "classic-import.local.yml"

if (-not (Test-Path $envFile)) {
  throw "Install trueRiver first with .\deploy\windows\Install-Triver.ps1, then configure Classic Import folders."
}

$selectedPaths = @($SourcePath | Where-Object { $_ })
if ($selectedPaths.Count -eq 0) {
  Write-Host "Enter one external media folder per line. Leave empty to finish."
  while ($true) {
    $path = Read-Host "Folder path"
    if (-not $path) {
      break
    }
    $selectedPaths += $path
  }
}
if ($selectedPaths.Count -eq 0) {
  throw "No folders selected."
}

$entries = @()
$slugs = @()
$resolvedPaths = @()
foreach ($path in $selectedPaths) {
  if (-not (Test-Path $path -PathType Container)) {
    throw "Not a directory: $path"
  }
  $resolved = [System.IO.Path]::GetFullPath($path)
  $base = Split-Path $resolved -Leaf
  $slugBase = ConvertTo-TriverSourceKey $base
  $slug = $slugBase
  $counter = 2
  while ($slugs -contains $slug) {
    $slug = "$slugBase-$counter"
    $counter += 1
  }
  $slugs += $slug
  $resolvedPaths += $resolved
  $entries += "$slug=/srv/triver-classic/$slug"
}

$lines = @(
  "# Generated by deploy/windows/Configure-ClassicImportSources.ps1",
  "services:"
)
foreach ($service in @("triver-backend", "triver-worker", "triver-beat")) {
  $lines += "  ${service}:"
  $lines += "    volumes:"
  for ($index = 0; $index -lt $slugs.Count; $index += 1) {
    $lines += "      - type: bind"
    $lines += "        source: $(ConvertTo-YamlQuoted (ConvertTo-TriverComposePath ($resolvedPaths[$index])))"
    $lines += "        target: /srv/triver-classic/$($slugs[$index])"
    $lines += "        read_only: true"
  }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($extraCompose, [string[]]$lines, $utf8NoBom)
Set-TriverEnvValue $envFile "TRIVER_CLASSIC_IMPORT_SOURCES" ($entries -join ";")
Set-TriverEnvValue $envFile "TRIVER_COMPOSE_EXTRA" $extraCompose

Write-Host "Classic Import folders configured:"
for ($index = 0; $index -lt $slugs.Count; $index += 1) {
  Write-Host "  $($slugs[$index]) -> $($resolvedPaths[$index])"
}
Write-Host "Restart trueRiver with:"
Write-Host "  .\deploy\windows\Start-Triver.ps1 -InstallRoot `"$($paths.Root)`""
