# Generated by Django 5.1.8 on 2026-05-19 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_artist_profile_images'),
        ('tags', '0002_tagvalue_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArtistTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='tagdefinition',
            name='uniq_tag_definition_scope_key',
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='visibility',
            field=models.CharField(choices=[('global', 'global'), ('personal', 'personal')], default='global', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='tagdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('visibility', 'global')), fields=('scope', 'key'), name='uniq_tag_definition_global_scope_key'),
        ),
        migrations.AddConstraint(
            model_name='tagdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('visibility', 'personal')), fields=('scope', 'key', 'owner'), name='uniq_tag_definition_personal_scope_key_owner'),
        ),
        migrations.AddField(
            model_name='albumtagassignment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='catalog.album'),
        ),
        migrations.AddField(
            model_name='albumtagassignment',
            name='tag_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_assignments', to='tags.tagvalue'),
        ),
        migrations.AddField(
            model_name='artisttagassignment',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='artisttagassignment',
            name='tag_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_assignments', to='tags.tagvalue'),
        ),
        migrations.AddConstraint(
            model_name='albumtagassignment',
            constraint=models.UniqueConstraint(fields=('album', 'tag_value'), name='uniq_album_tag_assignment'),
        ),
        migrations.AddConstraint(
            model_name='artisttagassignment',
            constraint=models.UniqueConstraint(fields=('artist', 'tag_value'), name='uniq_artist_tag_assignment'),
        ),
    ]
