#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REQUESTED_LOCAL_DIR="${TRIVER_LOCAL_DIR:-$ROOT_DIR/../triver-local}"
LOCAL_DIR="$(mkdir -p "$REQUESTED_LOCAL_DIR" && cd "$REQUESTED_LOCAL_DIR" && pwd)"
ENV_FILE="${TRIVER_ENV_FILE:-$LOCAL_DIR/.env}"
EXTRA_COMPOSE_FILE="$LOCAL_DIR/classic-import.local.yml"

if [ ! -f "$ENV_FILE" ]; then
  TRIVER_LOCAL_DIR="$LOCAL_DIR" "$ROOT_DIR/scripts/init-local-config.sh" >/dev/null
fi

env_value() {
  local key="$1"
  grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -n 1 | cut -d= -f2- || true
}

set_env_value() {
  local key="$1"
  local value="$2"
  if grep -qE "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
}

slugify() {
  local raw="$1"
  local slug
  slug="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_-]+/-/g; s/^-+//; s/-+$//')"
  if [ -z "$slug" ]; then
    slug="source"
  fi
  printf '%s\n' "$slug"
}

yaml_quote() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

paths=("$@")
if [ "${#paths[@]}" -eq 0 ]; then
  echo "Enter one external media folder per line. Leave empty to finish."
  while true; do
    printf 'Folder path: '
    IFS= read -r path || break
    [ -z "$path" ] && break
    paths+=("$path")
  done
fi

if [ "${#paths[@]}" -eq 0 ]; then
  echo "No folders selected." >&2
  exit 1
fi

entries=()
slugs=()
resolved_paths=()
for raw_path in "${paths[@]}"; do
  if [ ! -d "$raw_path" ]; then
    echo "Not a directory: $raw_path" >&2
    exit 1
  fi
  resolved="$(cd "$raw_path" && pwd)"
  base="$(basename "$resolved")"
  slug="$(slugify "$base")"
  original_slug="$slug"
  counter=2
  while printf '%s\n' "${slugs[@]}" | grep -qx "$slug"; do
    slug="${original_slug}-${counter}"
    counter=$((counter + 1))
  done
  slugs+=("$slug")
  resolved_paths+=("$resolved")
  entries+=("${slug}=/srv/triver-classic/${slug}")
done

{
  echo "# Generated by scripts/configure-classic-import-sources.sh"
  echo "services:"
  for service in triver-backend triver-worker triver-beat; do
    echo "  ${service}:"
    echo "    volumes:"
    for index in "${!slugs[@]}"; do
      echo "      - type: bind"
      echo "        source: \"$(yaml_quote "${resolved_paths[$index]}")\""
      echo "        target: /srv/triver-classic/${slugs[$index]}"
      echo "        read_only: true"
    done
  done
} > "$EXTRA_COMPOSE_FILE"

joined_entries="$(IFS=';'; echo "${entries[*]}")"
set_env_value TRIVER_CLASSIC_IMPORT_SOURCES "$joined_entries"
set_env_value TRIVER_COMPOSE_EXTRA "$EXTRA_COMPOSE_FILE"

cat <<EOF
Classic Import folders configured:
$(for index in "${!slugs[@]}"; do printf '  %s -> %s\n' "${slugs[$index]}" "${resolved_paths[$index]}"; done)

Updated:
  $ENV_FILE
  $EXTRA_COMPOSE_FILE

Restart trueRiver with:
  TRIVER_LOCAL_DIR="$LOCAL_DIR" ./scripts/deploy-local.sh
EOF
